version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data/pg:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - svc-network

  mydocs:
    build: ./mydocs
    image: mydocs
    container_name: mydocs-container
    ports:
      - "${MYDOCS_PORT}:8080"
    restart: on-failure
    networks:
      - svc-network
    depends_on:
      - postgres

  departs-coop:
    build: ./departs-coop
    image: departs-coop
    container_name: departs-coop-container
    ports:
      - "${DEPARTS_PORT}:8080"
    restart: on-failure
    networks:
      - svc-network
    depends_on:
      - mydocs

networks:
  svc-network:
    driver: bridge
